const USE_IPFS = false;

export const CDN_URL = "https://lil-darkie.b-cdn.net";

export const ASSETS = {
  fallTourTitle: USE_IPFS
    ? "https://bafybeiadtignohh24xmumfioqtyxfqzfjjm2r3zbyzttlgy3hyefqrpqpu.ipfs.w3s.link/fall-tour-title-small.png"
    : `${CDN_URL}/fall-tour-title-small.png`,
  fallTourTitleDark: USE_IPFS
    ? "https://bafybeibjkoxgizt4ykjcigk2sk5xjdr46gbq6icqi7zm3iyiqi24iyh3pq.ipfs.w3s.link/fall-tour-title-dark-small.png"
    : `${CDN_URL}/fall-tour-title-dark-small.png`,
  monsters: USE_IPFS
    ? "https://bafybeiazncfdwvwwsyjiiqo6a6rdmglpuhwsr7kdgilhugzk76rbl7poo4.ipfs.w3s.link/monsters-red.png"
    : `${CDN_URL}/monsters-red.png`,
  emo: USE_IPFS
    ? "https://bafybeihid2vzy64rho7b247tale4n2vhzcni75eqnerogwab4oxh7c7ezy.ipfs.w3s.link/emo.png"
    : `${CDN_URL}/emo.png`,
  billion: USE_IPFS
    ? "https://bafybeia2qhi76syvqulz3qxfvpkw22mkyxkscsriaeoe3rvaxacgwasm6y.ipfs.w3s.link/billion-peach.png"
    : `${CDN_URL}/billion-peach.png`,
  end: USE_IPFS
    ? "https://bafybeicy6fsnpnyjakxxbexk65vge7smfglw3pb5lpnmvtyxs2jmeyxpee.ipfs.w3s.link/end.png"
    : `${CDN_URL}/end.png`,
  voteGuy: USE_IPFS
    ? "https://bafybeifv3fop47jb7zvwx2awj7nt4lxudr3j543dydjbwc66dzwo2fdx2y.ipfs.w3s.link/vote_guy-small.png"
    : `${CDN_URL}/vote_guy-small.png`,
  paratrooper: USE_IPFS
    ? "https://bafybeigdv6qypf6b3ed73sweo2xkmop2osoljvjsyby6qgugr5xvr2p37e.ipfs.w3s.link/paratrooper-small.png"
    : `${CDN_URL}/paratrooper-small.png`,
  bottom: USE_IPFS
    ? "https://bafybeievfspc2ly3jdc4kiblhpsm3ou7vtaqqhxztr63lz3ajivelhajhe.ipfs.w3s.link/bottom-small.png"
    : `${CDN_URL}/bottom-small.png`,
  tv: USE_IPFS
    ? "https://bafybeibgknhli4czaontegb4j4646gbze6ooaji5mg6sv5q2kptqrp6e6u.ipfs.w3s.link/tv.jpg"
    : `${CDN_URL}/tv.jpg`,
  camo: USE_IPFS
    ? "https://bafybeibdevvavuiilnoblimtrr2cyytdzaokxzz34agqliczwoxw6xmvb4.ipfs.w3s.link/camo-small.png"
    : `${CDN_URL}/camo-small.png`,
  broken: USE_IPFS
    ? "https://bafybeiamtimm4yofjf6t7d2vdaoqhq6jx7xeru3eis3l7m2hh3sbgdltki.ipfs.w3s.link/broken.png"
    : `${CDN_URL}/broken.png`,
  melting: USE_IPFS
    ? "https://bafybeicb6mevonlxku4p3n6dg7qtkagejjzw6l7tt5c7v6kfo5xwvyjlgy.ipfs.w3s.link/melting.png"
    : `${CDN_URL}/melting.png`,
  lostSongs: USE_IPFS
    ? "https://bafybeidokhm3dkhmmjreyyz6xltsxvuwvz4wpzuawji22it3i4g43zyrea.ipfs.w3s.link/album.jpg"
    : `${CDN_URL}/lost-songs/album.jpg`,
  logo: USE_IPFS
    ? "https://bafybeihytsdrld7swcdb4qm5xkppnt3pq5n47ghigppronejfqpiob7uay.ipfs.w3s.link/logo-small.png"
    : `${CDN_URL}/logo-small.png`,
  logoYellow: USE_IPFS
    ? "https://bafybeidazdcrnw2nfv6joywrvsxavreqdrhua7m2zui3h4ybas7vog53b4.ipfs.w3s.link/logo-yellow.png"
    : `${CDN_URL}/logo-yellow.png`,
  face1: USE_IPFS
    ? "https://bafybeibagmtnngvblihdrnv5mf5rskwicpnd622sammapkzlzgyxqhmjrq.ipfs.w3s.link/face-1.png"
    : `${CDN_URL}/face/face-1.png`,
  face1Blink: USE_IPFS
    ? "https://bafybeidpfys2pi7tviwtqcw27nggbsrbpeqfunj5yvaa5y3val6hcz7l4q.ipfs.w3s.link/face-1-blink.png"
    : `${CDN_URL}/face/face-1-blink.png`,
  face2: USE_IPFS
    ? "https://bafybeictwkdzl2giujjdt7jcqs5karaztm3plr7evqla2yohxhhi3oohhq.ipfs.w3s.link/face-2.png"
    : `${CDN_URL}/face/face-2.png`,
  face3: USE_IPFS
    ? "https://bafybeigxegewjqth6ul7dhjztpj3qjy7clhle63er6v4la2w7sn5dvgch4.ipfs.w3s.link/face-3.png"
    : `${CDN_URL}/face/face-3.png`,
  face4: USE_IPFS
    ? "https://bafybeib36iujuzhdm6tijonea3dzlblovvym5niy3rh6et6o6rprr2cy4a.ipfs.w3s.link/face-4.png"
    : `${CDN_URL}/face/face-4.png`,
  face5: USE_IPFS
    ? "https://bafybeiade37jajch2gz2qfflyvw5e34morqcpxfakrtzirsiqibnlutumy.ipfs.w3s.link/face-5.png"
    : `${CDN_URL}/face/face-5.png`,
  face6: USE_IPFS
    ? "https://bafybeia4s25xjzxuhxxm7vxnipn7xgs5nahdtreyop4ct422mzmbydeaca.ipfs.w3s.link/face-6.png"
    : `${CDN_URL}/face/face-6.png`,
  face7: USE_IPFS
    ? "https://bafybeih2rwqtpedonfrhgnsd4ctg3t6eir5xzwlnqfhpmoxtqz5bq4vjdi.ipfs.w3s.link/face-7.png"
    : `${CDN_URL}/face/face-7.png`,
  menu: USE_IPFS
    ? "https://bafybeihd3hcwwqgadbmay3ac7duqxkiawqln4mwyv5qotqob5mbr3gblle.ipfs.w3s.link/menu.png"
    : `${CDN_URL}/menu.png`,
  spotifyWhiteIcon: USE_IPFS
    ? "https://bafybeifwpiff3t5ugopdff33gqvvxkhpbmi46nthcpvzhn7vj4uyp4wjxa.ipfs.w3s.link/Spotify_Icon_RGB_White.png"
    : `${CDN_URL}/icons/Spotify_Icon_RGB_White.png`,
  soundcloudIcon: USE_IPFS
    ? "https://bafybeigmjcm2gfnsrh2ewnn3o45ct5btmqcs4infepoz3l3ikpd7elveh4.ipfs.w3s.link/soundcloud.png"
    : `${CDN_URL}/icons/soundcloud.png`,
  youtubeIcon: USE_IPFS
    ? "https://bafybeibimogjsg7cuxtuyzrz2pd5wg33chvkcetyyjmkc6rud7au5xvu2y.ipfs.w3s.link/youtube.png"
    : `${CDN_URL}/icons/youtube.png`,
  closeIcon: USE_IPFS
    ? "https://bafybeiftm46cbqzlm5qwliqcbj7yq2zzyqqorxah7i7qekamahwvwejjyu.ipfs.w3s.link/close.png"
    : `${CDN_URL}/icons/close.png`,
  dashIcon: USE_IPFS
    ? "https://bafybeieh52n2jlhxezbwcoeq436dctgwt4355dxdvs2jweoog5qbsko6hq.ipfs.w3s.link/dash.png"
    : `${CDN_URL}/icons/dash.png`,
  mushroom: USE_IPFS
    ? "https://bafybeielrogk7tevky4xmiwtdbvbczawkv4whk5oqrz5ro4q6nhvm5kaoe.ipfs.w3s.link/mushroom-small.png"
    : `${CDN_URL}/mushroom-small.png`,
  plane1: USE_IPFS
    ? "https://bafybeicgvbqgs6frb4arm3454vs3ir7j76nztj6m56cjknvysuhrizyage.ipfs.w3s.link/plane-1-small.png"
    : `${CDN_URL}/plane-1-small.png`,
  plane2: USE_IPFS
    ? "https://bafybeic4tgbjxxik7y5nxjg27mziveq3emqmuy24bc5fdi4bpaxlplhahm.ipfs.w3s.link/plane-2-small.png"
    : `${CDN_URL}/plane-2-small.png`,
  frameLeft: USE_IPFS
    ? "https://bafybeicnzhlaniy2xnhgyhhbdispwbjhoeft2nm7qf2mlr7mbbmm3xamle.ipfs.w3s.link/frame-left-small.png"
    : `${CDN_URL}/frame-left-small.png`,
  frameRight: USE_IPFS
    ? "https://bafybeiflitvw42o6ebskzdhsklrhmxwqqjoudert6fnd6xmzw7xjos5slm.ipfs.w3s.link/frame-right-small.png"
    : `${CDN_URL}/frame-right-small.png`,
  frameBottom: USE_IPFS
    ? "https://bafybeihkf4r37tsgn2ejpxd4mdxt7dbn62a5gnyyyeqqpxlru75uiwch44.ipfs.w3s.link/frame-bottom-small.png"
    : `${CDN_URL}/frame-bottom-small.png`,
  unIcon: USE_IPFS
    ? "https://bafybeihsn3py5lhnhj7mjidbq7qfz2fhlotrcrhvzhcfo5jtcvaecnmybm.ipfs.w3s.link/un.png"
    : `${CDN_URL}/un.png`,
  arrowIcon: USE_IPFS
    ? "https://bafybeigmfdtfgvvazx7tpdlbuzigaggbnuppycvqcjbilgovpo3zhu33ou.ipfs.w3s.link/arrow.png"
    : `${CDN_URL}/icons/arrow.png`,
  gunIcon: USE_IPFS
    ? "https://bafybeibc5xq4i5qykh6o7kqpf47z6jfg2mqg2lwtnbnkjplfpvvdgngyfq.ipfs.w3s.link/gun.png"
    : `${CDN_URL}/icons/gun.png`,
  skullIcon: USE_IPFS
    ? "https://bafybeiaklypdtymjhhvkuwznwbroxaafwsppjytjgygqkiiaoapdrvtysu.ipfs.w3s.link/skull.png"
    : `${CDN_URL}/icons/skull.png`,
  graveIcon: USE_IPFS
    ? "https://bafybeidrdzlml6vpwearcge2yfmy5yfl7q7uzscplifg2z5tfzyge5w4eu.ipfs.w3s.link/grave.png"
    : `${CDN_URL}/icons/grave.png`,
  boozeIcon: USE_IPFS
    ? "https://bafybeicv327jp5a36w3s6cqq4j4uncfnvd2amz56dy76j6r4oz5jl3naxq.ipfs.w3s.link/booze.png"
    : `${CDN_URL}/icons/booze.png`,
  knifeIcon: USE_IPFS
    ? "https://bafybeigvscewb3phgrfoltmsfz46qd74vtlaf4nok25tcmdepmlubshaau.ipfs.w3s.link/knife.png"
    : `${CDN_URL}/icons/knife.png`,
  spotifyGreenIcon: USE_IPFS
    ? "https://bafybeieslldwlnumivudgwlxwhebsvlx7yvzupnxgyqesfyo2tujyf24ua.ipfs.w3s.link/Spotify_Icon_RGB_Green.png"
    : `${CDN_URL}/icons/Spotify_Icon_RGB_Green.png`,
  spotifyGreenLogo: USE_IPFS
    ? "https://bafybeieve3hkqxwrkku2mwhuo76mymglw2gll2slweyyet7bi2mys3t5tq.ipfs.w3s.link/Spotify_Logo_RGB_Green.png"
    : `${CDN_URL}/icons/Spotify_Logo_RGB_Green.png`,
};
